<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ReleaseVersion>1.0.1</ReleaseVersion>
    <Version>1.0.1</Version>
    <TargetFramework>net7.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageId>rob_bl8ke.Qik</PackageId>
    <Authors>Rob Blake</Authors>
    <Company>Rob Blake</Company>
    <Description>Simple script-based generation tool</Description>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <PackageTags>Generate,Produce,Spawn,Generator</PackageTags>
    <RepositoryUrl>https://github.com/rob-bl8ke/Qik</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="QikTests" /> <!-- [assembly: InternalsVisibleTo("CustomTest1")] -->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QikAntlr\QikAntlr.csproj" />
  </ItemGroup>

<!-- 
    Avoid
    System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional.
 -->
<ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
</ItemGroup>

</Project>
