//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\bobbyache\Qik\Code\Current\QikAntlr\QikTemplate.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CygSoft.Qik.Antlr {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="QikTemplateParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IQikTemplateListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplate([NotNull] QikTemplateParser.TemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplate([NotNull] QikTemplateParser.TemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.inputDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputDecl([NotNull] QikTemplateParser.InputDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.inputDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputDecl([NotNull] QikTemplateParser.InputDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.uiWidget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUiWidget([NotNull] QikTemplateParser.UiWidgetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.uiWidget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUiWidget([NotNull] QikTemplateParser.UiWidgetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.uiWidgetProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUiWidgetProperty([NotNull] QikTemplateParser.UiWidgetPropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.uiWidgetProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUiWidgetProperty([NotNull] QikTemplateParser.UiWidgetPropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.uiWidgetKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUiWidgetKey([NotNull] QikTemplateParser.UiWidgetKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.uiWidgetKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUiWidgetKey([NotNull] QikTemplateParser.UiWidgetKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDecl([NotNull] QikTemplateParser.FuncDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDecl([NotNull] QikTemplateParser.FuncDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] QikTemplateParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] QikTemplateParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] QikTemplateParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] QikTemplateParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.compExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompExpr([NotNull] QikTemplateParser.CompExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.compExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompExpr([NotNull] QikTemplateParser.CompExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.concatExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConcatExpr([NotNull] QikTemplateParser.ConcatExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.concatExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConcatExpr([NotNull] QikTemplateParser.ConcatExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.iffExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIffExpr([NotNull] QikTemplateParser.IffExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.iffExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIffExpr([NotNull] QikTemplateParser.IffExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.iffTrueStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIffTrueStat([NotNull] QikTemplateParser.IffTrueStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.iffTrueStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIffTrueStat([NotNull] QikTemplateParser.IffTrueStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.iffFalseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIffFalseStat([NotNull] QikTemplateParser.IffFalseStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.iffFalseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIffFalseStat([NotNull] QikTemplateParser.IffFalseStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.ifExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfExpr([NotNull] QikTemplateParser.IfExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.ifExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfExpr([NotNull] QikTemplateParser.IfExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStat([NotNull] QikTemplateParser.IfStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStat([NotNull] QikTemplateParser.IfStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.elseIfStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfStat([NotNull] QikTemplateParser.ElseIfStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.elseIfStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfStat([NotNull] QikTemplateParser.ElseIfStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.switchExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchExpr([NotNull] QikTemplateParser.SwitchExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.switchExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchExpr([NotNull] QikTemplateParser.SwitchExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.switchStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStat([NotNull] QikTemplateParser.SwitchStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.switchStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStat([NotNull] QikTemplateParser.SwitchStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.caseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseStat([NotNull] QikTemplateParser.CaseStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.caseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseStat([NotNull] QikTemplateParser.CaseStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.elseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStat([NotNull] QikTemplateParser.ElseStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.elseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStat([NotNull] QikTemplateParser.ElseStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] QikTemplateParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] QikTemplateParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.funcArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncArg([NotNull] QikTemplateParser.FuncArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.funcArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncArg([NotNull] QikTemplateParser.FuncArgContext context);
}
} // namespace CygSoft.Qik.Antlr
