//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\bobbyache\Qik\Code\Current\QikAntlr\QikTemplate.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CygSoft.Qik.Antlr {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IQikTemplateListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class QikTemplateBaseListener : IQikTemplateListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplate([NotNull] QikTemplateParser.TemplateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplate([NotNull] QikTemplateParser.TemplateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.inputDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputDecl([NotNull] QikTemplateParser.InputDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.inputDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputDecl([NotNull] QikTemplateParser.InputDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.uiWidget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUiWidget([NotNull] QikTemplateParser.UiWidgetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.uiWidget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUiWidget([NotNull] QikTemplateParser.UiWidgetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.uiWidgetProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUiWidgetProperty([NotNull] QikTemplateParser.UiWidgetPropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.uiWidgetProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUiWidgetProperty([NotNull] QikTemplateParser.UiWidgetPropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.uiWidgetKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUiWidgetKey([NotNull] QikTemplateParser.UiWidgetKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.uiWidgetKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUiWidgetKey([NotNull] QikTemplateParser.UiWidgetKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDecl([NotNull] QikTemplateParser.FuncDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDecl([NotNull] QikTemplateParser.FuncDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] QikTemplateParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] QikTemplateParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] QikTemplateParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] QikTemplateParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.compExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompExpr([NotNull] QikTemplateParser.CompExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.compExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompExpr([NotNull] QikTemplateParser.CompExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.concatExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConcatExpr([NotNull] QikTemplateParser.ConcatExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.concatExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConcatExpr([NotNull] QikTemplateParser.ConcatExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.iffExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIffExpr([NotNull] QikTemplateParser.IffExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.iffExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIffExpr([NotNull] QikTemplateParser.IffExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.iffTrueStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIffTrueStat([NotNull] QikTemplateParser.IffTrueStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.iffTrueStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIffTrueStat([NotNull] QikTemplateParser.IffTrueStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.iffFalseStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIffFalseStat([NotNull] QikTemplateParser.IffFalseStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.iffFalseStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIffFalseStat([NotNull] QikTemplateParser.IffFalseStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.ifExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfExpr([NotNull] QikTemplateParser.IfExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.ifExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfExpr([NotNull] QikTemplateParser.IfExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStat([NotNull] QikTemplateParser.IfStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStat([NotNull] QikTemplateParser.IfStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.elseIfStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIfStat([NotNull] QikTemplateParser.ElseIfStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.elseIfStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIfStat([NotNull] QikTemplateParser.ElseIfStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.switchExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchExpr([NotNull] QikTemplateParser.SwitchExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.switchExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchExpr([NotNull] QikTemplateParser.SwitchExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.switchStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStat([NotNull] QikTemplateParser.SwitchStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.switchStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStat([NotNull] QikTemplateParser.SwitchStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.caseStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseStat([NotNull] QikTemplateParser.CaseStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.caseStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseStat([NotNull] QikTemplateParser.CaseStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.elseStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStat([NotNull] QikTemplateParser.ElseStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.elseStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStat([NotNull] QikTemplateParser.ElseStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc([NotNull] QikTemplateParser.FuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc([NotNull] QikTemplateParser.FuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.funcArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncArg([NotNull] QikTemplateParser.FuncArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.funcArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncArg([NotNull] QikTemplateParser.FuncArgContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace CygSoft.Qik.Antlr
